# Generated by Django 3.0.1 on 2019-12-25 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userl', models.CharField(max_length=100, verbose_name='userl')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('ncode', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nコード')),
                ('ncode_int', models.IntegerField(unique=True, verbose_name='数字版Nコード')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='NovelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(verbose_name='あらすじ')),
                ('big_genre', models.IntegerField(choices=[(1, '恋愛'), (2, 'ファンタジー'), (3, '文芸'), (4, 'SF'), (99, 'その他'), (98, 'ノンジャンル')], verbose_name='大ジャンル')),
                ('genre', models.IntegerField(choices=[(101, '異世界〔恋愛〕'), (102, '現実世界〔恋愛〕'), (201, 'ハイファンタジー〔ファンタジー〕'), (202, 'ローファンタジー〔ファンタジー〕'), (301, '純文学〔文芸〕'), (302, 'ヒューマンドラマ〔文芸〕'), (303, '歴史〔文芸〕'), (304, '推理〔文芸〕'), (305, 'ホラー〔文芸〕'), (306, 'アクション〔文芸〕'), (307, 'コメディー〔文芸〕'), (401, 'VRゲーム〔SF〕'), (402, '宇宙〔SF〕'), (403, '空想科学〔SF〕'), (404, 'パニック〔SF〕'), (9901, '童話〔その他〕'), (9902, '詩〔その他〕'), (9903, 'エッセイ〔その他〕'), (9904, 'リプレイ〔その他〕'), (9999, 'その他〔その他〕'), (9801, 'ノンジャンル〔ノンジャンル〕')], verbose_name='ジャンル')),
                ('first_publication_date', models.DateTimeField(verbose_name='初回掲載日')),
                ('last_publication_date', models.DateTimeField(verbose_name='最終掲載日')),
                ('is_serial', models.BooleanField(verbose_name='連載')),
                ('episode_num', models.IntegerField(verbose_name='全話数')),
                ('length', models.IntegerField(verbose_name='文字数')),
                ('is_stop', models.BooleanField(verbose_name='長期連載停止中')),
                ('writer_device', models.IntegerField(choices=[(1, '携帯のみ'), (2, 'PCのみ'), (3, 'PCと携帯')], verbose_name='投稿時仕様端末')),
                ('total_point', models.IntegerField(verbose_name='総合評価ポイント')),
                ('daily_point', models.IntegerField(verbose_name='日韓ポイント')),
                ('weekly_rating_point', models.IntegerField(verbose_name='週間ポイント')),
                ('monthly_rating_point', models.IntegerField(verbose_name='月間ポイント')),
                ('quarter_rating_point', models.IntegerField(verbose_name='四半期ポイント')),
                ('yearly_rating_point', models.IntegerField(verbose_name='年間ポイント')),
                ('bookmark_num', models.IntegerField(verbose_name='ブックマーク数')),
                ('impression_num', models.IntegerField(verbose_name='感想数')),
                ('review_num', models.IntegerField(verbose_name='レビュー数')),
                ('all_point', models.IntegerField(verbose_name='評価点')),
                ('illust_num', models.IntegerField(verbose_name='挿絵数')),
                ('talking_row_rate', models.IntegerField(verbose_name='小説内の会話率')),
                ('updated_at', models.DateTimeField(verbose_name='更新日時')),
                ('keywords', models.ManyToManyField(related_name='novels', to='narou.KeyWord', verbose_name='キーワード')),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='narou.Novel')),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='narou.Writer', verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='当該話数')),
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='最終改稿日時')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='narou.Novel', verbose_name='物語')),
            ],
        ),
    ]
