# Generated by Django 3.0.1 on 2019-12-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noveldetail',
            name='episode_num',
        ),
        migrations.AddField(
            model_name='novel',
            name='max_episode_num',
            field=models.IntegerField(default=0, verbose_name='全話数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='ncode_int',
            field=models.IntegerField(blank=True, unique=True, verbose_name='数字版Nコード'),
        ),
        migrations.AlterField(
            model_name='noveldetail',
            name='writer_device',
            field=models.IntegerField(choices=[(1, '携帯のみ'), (2, 'PCのみ'), (3, 'PCと携帯')], verbose_name='投稿時使用端末'),
        ),
    ]
