# Generated by Django 3.0.1 on 2020-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0004_auto_20191230_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='章'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(verbose_name='話'),
        ),
    ]
