# Generated by Django 3.0.1 on 2020-02-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0005_auto_20200109_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='narou.Novel', verbose_name='小説'),
        ),
    ]
