# Generated by Django 3.0.1 on 2020-02-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0006_auto_20200215_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='writer_nickname',
            field=models.CharField(default='', max_length=100, verbose_name='ペンネーム'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='all_novel_length',
            field=models.IntegerField(default=0, verbose_name='小説累計文字数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='all_total_point',
            field=models.IntegerField(default=0, verbose_name='合計総合評価ポイント'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='novel_count',
            field=models.IntegerField(default=0, verbose_name='小説投稿数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='ruby',
            field=models.CharField(default='', max_length=100, verbose_name='ふりがな'),
            preserve_default=False,
        ),
    ]
