# Generated by Django 3.1 on 2020-08-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0008_auto_20200216_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='セリフ')),
                ('partial_of', models.IntegerField(choices=[(1, '本文'), (2, 'まえがき'), (3, 'あとがき')], verbose_name='区分')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='narou.episode', verbose_name='話')),
            ],
        ),
    ]
