# Generated by Django 3.1 on 2020-08-19 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('narou', '0009_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='readers',
            field=models.ManyToManyField(related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='読者'),
        ),
    ]
