# Generated by Django 3.1.2 on 2020-10-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0010_novel_readers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='識別用文字列')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('file', models.ImageField(upload_to='illusts/', verbose_name='画像')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illusts', to='narou.episode', verbose_name='話')),
            ],
        ),
    ]
