# Generated by Django 3.1.2 on 2020-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narou', '0011_illust'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='illust_count',
            field=models.IntegerField(default=0, verbose_name='イラスト数'),
        ),
    ]
