version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - nginx
    environment:
      DOMAINS: 'localhost -> http://nginx:1204/, scrapy.localhost -> http://nginx:1205/'
      # DOMAINS: 'localhost -> http://nginx:1204/, [IP_ADDRESS] -> http://nginx:1204/'
      STAGE: 'local'
      #STAGE: 'production'
    ports:
      - '80:80'
      - '443:443'

  nginx:
    build:
      context: ./docker
      dockerfile: NginxDockerfile
    container_name: narou_nginx
    depends_on:
      - node
    hostname: nginx
    ports:
      - "1204:1204"
      - "1205:1205"
    volumes:
      - "./docker/nginx/:/etc/nginx/"
      - "staticdata:/opt/static/"
      - "dist:/opt/dist/"
      - "./log:/var/log/nginx/"

  node:
    build:
      context: ./docker/
      dockerfile: NodeDockerfile
    container_name: narou_node
    depends_on:
      - python
    hostname: node
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
#    command: bash -c "npm install && npm run build && npm run start"
    environment:
      NODE_MAX_OLD_SPACE_SIZE: 12288
#      BASE_URL: "https://[IP_ADDRESS]"
    volumes:
      - "./nuxt:/src"
      - "dist:/src/dist/"
    working_dir: /src

  python:
    build:
      context: ./
      dockerfile: ./docker/PythonDockerfile
    image: narou_python

  django:
    image: narou_python
    container_name: narou_django
    depends_on:
      - python
    hostname: django
    ports:
      - "8000:8000"
    command: bash -c "sleep 5; python manage.py makemigrations && python manage.py migrate --run-syncdb && python manage.py collectstatic --noinput && gunicorn narou_scraping.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/src
      - "staticdata:/opt/static/"
    working_dir: /src

  scrapy:
    image: narou_python
    container_name: narou_scrapy
    depends_on:
      - python
    hostname: scrapy
    ports:
      - "6800:6800"
    command: bash -c "sleep 5; scrapyd && scrapyd-deploy -p narou_scraper"
    volumes:
      - .:/src
      - "staticdata:/opt/static/"
    working_dir: /src

volumes:
  staticdata:
  dist:
